#!/bin/sh
exec tail -n +3 $0

menuentry "Boot from UUID" {
    search --no-floppy --fs-uuid --set=root --hint='usb0,gpt2' --hint='mmcblk0,gpt2' B921B045-1DF0-41C3-AF44-4C6F280D3FAE
    echo    'Loading Linux 6.8.0-rc4 ...'
    linux /boot/vmlinuz-6.8.0-rc4 root=LABEL=rootfs rw rootwait
    echo    'Loading initial ramdisk ...'
    initrd /boot/initrd.img-6.8.0-rc4
    devicetree /boot/dtb/broadcom/bcm2711-rpi-4-b.dtb
}
