#!/bin/sh
exec tail -n +3 $0

menuentry "Boot from UUID" {
    search --no-floppy --fs-uuid --set=root --hint='usb0,gpt2' --hint='mmcblk0,gpt2' --hint='mmcblk1,gpt2' B921B045-1DF0-41C3-AF44-4C6F280D3FAE
    echo    'Loading Linux 6.14.0-rc2-v8-16k ...'
    linux /boot/vmlinuz-6.14.0-rc2-v8-16k root=LABEL=rootfs rw rootwait video=HDMI-A-1:1920x1080@60
    echo    'Loading initial ramdisk ...'
    initrd /boot/initrd.img-6.14.0-rc2-v8-16k
    devicetree /boot/dtb/broadcom/bcm2712-rpi-5-b.dtb
}
