#!/bin/sh
exec tail -n +3 $0

menuentry "Boot from UUID" {
    search --no-floppy --fs-uuid --set=root --hint='usb0,gpt2' --hint='mmcblk0,gpt2' B921B045-1DF0-41C3-AF44-4C6F280D3FAE
    echo    'Loading Linux 6.13.0-rc3 ...'
    linux /boot/vmlinuz-6.13.0-rc7-v8-16k+ root=UUID=b921b045-1df0-41c3-af44-4c6f280d3fae rw rootwait
    echo    'Loading initial ramdisk ...'
    initrd /boot/initrd.img-6.13.0-rc7-v8-16k+
    devicetree /boot/dtb/broadcom/bcm2712-rpi-5-b.dtb
}
